INSERT INTO movies (title, rating, synopsis, categories)
VALUES ('Get Out', 'R', '', 'Horror')
VALUES ('Conjuring', 'R', '', 'Horror')
VALUES ('The Curse of La Llorona', 'R', '', 'Horror')
VALUES ('The Cabin in the Woods', 'R', '', 'Horror')
VALUES ('Hereditary', 'R', '', 'Horror')
VALUES ('Hangover', 'R', '', 'Comedy')
VALUES ('Step Brothers', 'R', '', 'Comedy')
VALUES ('Dumb & Dumber', 'PG-13', 'Comedy')
VALUES ('Major Payne', 'PG-13', '', 'Comedy')
VALUES ('Jumanji: The Next Level', 'PG-13', '', 'Comedy')
VALUES ('Aqua Man', 'PG-13', '', 'Action')
VALUES ('The Fate of the Furious', 'PG-13', '', 'Action')
VALUES ('Divergent', 'PG-13', '', 'Action')
VALUES ('John Wick', 'R', '', 'Action')
VALUES ('The Equalizer', 'R', '', 'Action')
VALUES ('Pacific Rim', 'PG-13', '', 'Sci-Fi')
VALUES ('Akira', 'R','', 'Sci-Fi')
VALUES ('Godzilla: King of the Monsters', 'PG-13', '', 'Sci-Fi')
VALUES ('Ready Player One', 'PG-13', '', 'Sci-Fi')
VALUES ('Kong: Skull Island', 'PG-13', '', 'Sci-Fi')